name: Merge to Staging
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> staging
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: staging
          github_token: ${{ secrets.REPO_TOKEN }}

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
#          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
